export const Data = [
  {
    id: '1',
    url: require('../assets/image/ps1.jpeg'),
    nama: 'dr. Chandra I, Sp.KJ',
    spesialis: 'Percintaan',
    hari: 'Senin, Selasa',
    tarif: 'Rp 150.000',
  },
  {
    id: '2',
    url: require('../assets/image/ps3.jpeg'),
    nama: 'dr. Ahmad S H D, Sp.KJ',
    spesialis: 'Anak',
    hari: "Selasa, Rabu, Jum'at",
    tarif: 'Rp 250.000',
  },
  {
    id: '3',
    url: require('../assets/image/ps5.jpeg'),
    nama: 'dr. Tesaviani K, Sp.KJ',
    spesialis: 'Keluarga',
    hari: 'Rabu, Kamis',
    tarif: 'Rp 175.000',
  },
  {
    id: '4',
    url: require('../assets/image/ps6.jpeg'),
    nama: 'dr. Yossy A I, Sp.KJ',
    spesialis: 'Anak',
    hari: 'Senin, Kamis, Sabtu',
    tarif: 'Rp 300.000',
  },
  {
    id: '5',
    url: require('../assets/image/ps2.jpeg'),
    nama: 'dr. Mustafa M A, Sp.KJ',
    spesialis: 'Percintaan',
    hari: 'Selasa, Rabu, Minggu',
    tarif: 'Rp 350.000',
  },
  {
    id: '6',
    url: require('../assets/image/ps7.jpeg'),
    nama: 'dr. Dian P, Sp.KJ',
    spesialis: 'Anak',
    hari: 'Kamis, Jumat, Sabtu',
    tarif: 'Rp 200.000',
  },
  {
    id: '7',
    url: require('../assets/image/ps4.jpeg'),
    nama: 'dr. Dyani P V, Sp.KJ',
    spesialis: 'Keluarga',
    hari: 'Senin, Rabu, Jumat',
    tarif: 'Rp 240.000',
  },
];
